FROM node:24-alpine AS base

WORKDIR /usr/local/app

RUN npm install -g pnpm

# copy dependency configuration
COPY web/client/package.json web/client/pnpm-*.yaml ./

RUN pnpm ci

FROM base AS dev

EXPOSE 4200

# add host argument to allow non-localhost connections
ENTRYPOINT ["pnpm", "start", "--host=0.0.0.0"]

FROM base AS test

COPY web/client/ .

# add host argument to allow non-localhost connections
ENTRYPOINT ["pnpm", "test"]